services:
  comfy_ui:
    container_name: comfy_no_0
    image: rhoninn11/comfy_docker:v3
    # By default Part-DB will be running under Port 8080, you can change it here
    ports:
      - '8188:8188'
      - '11434:11434'
      - '50051:50051'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu]
    volumes:
      # ai models
      - $COMFY/models:/mea/comfy_ui/models
      - $OLLAMA/models:/root/.ollama/models
      
      # dev
      # - $MEA/src:/mea/mea_comfy/src
      # - $MEA/proto:/mea/mea_comfy/proto
      # - $MEA/assets:/mea/dev_bridge/assets
      # - $MEA/misc:/mea/dev_bridge/misc
      - $MEA:/mea/mea_comfy

      # for gui comfy ui
      # - $MEA/fs/docker/plug_snap:/mea/comfy_ui/custom_nodes/ComfyUI-Manager/snapshots
      # - $MEA/fs/docker/out:/mea/comfy_ui/output
      - $MEA/docker/system:/mea/system

    command: /mea/system/start_alt.sh
    # command: sleep 1000 
