services:
  comfy_ui:
    container_name: comfy_no_0
    image: rhoninn11/comfy_docker:v3
    # By default Part-DB will be running under Port 8080, you can change it here
    ports:
      - '8188:8188'
      - '11434:11434'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes:
      - $COMFY/models:/mea/comfy_ui/models
      - $OLLAMA/models:/root/.ollama/models
      
      - $MEA/docker/system:/mea/system
      - $MEA/assets:/mea/dev_bridge/assets
      - $MEA/other:/mea/dev_bridge/misc

      - $MEA/fs/docker/plug_snap:/mea/comfy_ui/custom_nodes/ComfyUI-Manager/snapshots
      - $MEA/fs/docker/out:/mea/comfy_ui/output
    command: /mea/system/start_alt.sh
    # command: sleep 1000 
